dnsjava/dnsjava

org/xbill/DNS/spi/DNSJavaNameServiceDescriptor.java
Using `Thread.currentThread().getContextClassLoader()` since that would probably cover the most bases, and is the suggested fix via pmd: https://pmd.github.io/latest/pmd_rules_java_errorprone.html#useproperclassloader
=> Fixes #26 NPE registering NameService

pom.xml
Per comment in https://github.com/dnsjava/dnsjava/issues/1#issuecomment-493774420
> when I see how much impact the other API changes will have. E.g. adding generics will not necessarily break APIs.
+1 on ensuring APIs don't break.  With this plugin, the build will fail when it detects incompatible API changes, compared to the previous version.  Also gives some insight/sanity checks on non-breaking changes (adding to API, removing method identical to superclass' implementation, etc.).
=> Adds japicmp plugin to ensure compatibility

org/xbill/DNS/Message.java, tests/org/xbill/DNS/MessageTest.java
This is the patch for the fix of the issue #60 "Miscount in Message.sectionToWire" in the old SourceForge issue system I opened back then.
=> Miscount in Message.sectionToWire

src/main/java/org/xbill/DNS/Master.java, src/main/java/org/xbill/DNS/Tokenizer.java, src/test/java/org/xbill/DNS/MasterTest.java, src/test/resources/zonefileEx1, src/test/resources/zonefileInvalidGenRange, src/test/resources/zonefileInvalidGenType, src/test/resources/zonefileInvalidTSIG
* Removing the private TokenizerException since it seems to just cause more confusion than help -- seems better to have this consistently under TextParseException.  It's functionality (filename + line number in the message) still exists in the exception method.
* Added an initial MasterTest with example zone files to help sanity check records in zone files
=> Remove TokenizerException

pom.xml
=> Add license file to meta-inf

pom.xml, src/main/java/jnamed.java, src/main/java/org/xbill/DNS/Cache.java, src/main/java/org/xbill/DNS/DNSSEC.java, src/main/java/org/xbill/DNS/Lookup.java, src/main/java/org/xbill/DNS/Message.java, src/main/java/org/xbill/DNS/RRset.java, src/main/java/org/xbill/DNS/Record.java, src/main/java/org/xbill/DNS/ResolverConfig.java, src/main/java/org/xbill/DNS/SetResponse.java, src/main/java/org/xbill/DNS/Update.java, src/main/java/org/xbill/DNS/Zone.java, src/test/java/org/xbill/DNS/DNSSECTest.java, src/test/java/org/xbill/DNS/RRsetTest.java, src/test/java/org/xbill/DNS/SetResponseTest.java, src/test/java/org/xbill/DNS/apps/primary.java
Do you agree with the new API on RRset? This is the first real breaking change. I thought about adding an overload or making rrs() generic if the set is expected to contain only one type.
=> Lists for RRset

src/main/java/org/xbill/DNS/Master.java
- Add support for disabling $INCLUDE when parsing master files
- Optionally throw an exception (for bubbling up) when $INCLUDE processing is disabled, and the token is encountered
=> Add support for disabling $INCLUDE

src/main/java/org/xbill/DNS/CookieOption.java, src/main/java/org/xbill/DNS/EDNSOption.java, src/main/java/org/xbill/DNS/Rcode.java, src/main/java/org/xbill/DNS/TcpKeepaliveOption.java, src/test/java/org/xbill/DNS/CookieOptionTest.java, src/test/java/org/xbill/DNS/RcodeTest.java, src/test/java/org/xbill/DNS/TcpKeepaliveOptionTest.java
I have implemented EDNS options for DNS Cookies (RFC 7873) and for TCP Keepalive (RFC 7828). When adding the BADCOOKIE RCODE to the Rcode class, I discovered that for TKEY, two RCODEs were missing and and another was added to the tsigrcodes instance, which is IMHO wrong. I moved the latter to the regular rcodes instance. As this is fully included into the tsigrcodes instance, it should not break any existing code. Finally, I fixed one test class, as the RCODE 20 is no longer a "reserved" value, but actually used.
It would be nice if you could eventually merge my additions and changes into the trunk. In case of any questions or problems, feel free to contact me.
=> addition of EDNS Cookie and TCP Keepalive Options

src/main/java/org/xbill/DNS/DNSOutput.java, src/main/java/org/xbill/DNS/TSIG.java, src/main/java/org/xbill/DNS/ZoneTransferIn.java, src/main/java/org/xbill/DNS/tools/dig.java, src/main/java/org/xbill/DNS/tools/jnamed.java, src/main/java/org/xbill/DNS/tools/update.java, src/main/java/org/xbill/DNS/tools/xfrin.java
- Remove duplicate code in generate/verify by adding a parameter
for the difference between "full" and "intermediate" signatures.
- Handle truncated signatures in streams
- Move time validation as per draft-ietf-dnsop-rfc2845bis
- Add trace dump of signature input data
Closes #109
=> Refactor TSIG handling

src/main/java/org/xbill/DNS/AAAARecord.java, src/test/java/org/xbill/DNS/AAAARecordTest.java
1. let AAAARecord support IPv4 Address.
2. use ::ffff:x.x.x.x instead of 0:0:0:0:ffff:xx:xx, more readable
=> Support IPv4 mapped IPv6 address in AAAA record

src/main/java/org/xbill/DNS/SVCBBase.java, src/test/java/org/xbill/DNS/SVCBRecordTest.java
Fix bug with parsing SVCB/HTTPS records from text where the Tokenizer is not properly reset at the end of the line.  The individual record parsing works correctly, but this was breaking the parsing of master zone files with SVCB or HTTPS records in them.
=> Fix bug with SVCB/HTTPS parsing of master file format

src/test/java/org/xbill/DNS/RecordTest.java
The previous import was from the junit 4 classes that ships with robolectric, which seems like it was a mistake.
=> Use fail() from junit

src/main/java/org/xbill/DNS/config/ResolverConfigProvider.java, src/test/java/org/xbill/DNS/LookupTest.java
Trying to hit as many code paths in the Lookup.run() as possible. Seems prudent before refactoring :)
=> Increase test coverage in LookupTest

src/main/java/org/xbill/DNS/Name.java, src/test/java/org/xbill/DNS/NameTest.java
The Name() constructor will currently fail if it's length() would
end up being longer than MAXNAME (255). However, there is an edge
case where a relative name can be exactly MAXNAME long. This is
legal but the lookup mechanism will then fail to make the name
absolute by appending an empty label to be able to use it for
lookups.
=> Have constructing relative Name with length() == MAXNAME fail

lombok.config, pom.xml, src/main/java/org/xbill/DNS/lookup/InvalidZoneDataException.java, src/main/java/org/xbill/DNS/lookup/LookupFailedException.java, src/main/java/org/xbill/DNS/lookup/LookupResult.java, src/main/java/org/xbill/DNS/lookup/LookupSession.java, src/main/java/org/xbill/DNS/lookup/NoSuchDomainException.java, src/main/java/org/xbill/DNS/lookup/NoSuchRRSetException.java, src/main/java/org/xbill/DNS/lookup/RedirectOverflowException.java, src/main/java/org/xbill/DNS/lookup/ServerFailedException.java, src/test/java/org/xbill/DNS/LookupTest.java, src/test/java/org/xbill/DNS/lookup/LookupResultTest.java, src/test/java/org/xbill/DNS/lookup/LookupSessionTest.java
I have started experimenting with an asynchronous lookup mechanism. Please note that this is a draft and not not feature complete. I just want to give the opportunity to gather some early feedback. In particular I am curious to to hear about:
* The name `DNSSession` for the new long lived API endpoint. Session is kind of vague on purpose, to allow it to have other public methods in the future that interact with DNS servers. I want to avoid Session because of the inconvenience of having it clash with for example the Session classes in the Neo4j or Cassandra.
* What do we think about putting an exception hierarchy in a separate module? My main reason for going there is that the org.xbill.DNS module is pretty crowded, but this is a weak preference.
The idea is to implement the following:
* …
=> Introduce an asynchronous lookup API

src/main/java/org/xbill/DNS/ExtendedResolver.java
`lbStart.updateAndGet(i -> i++ % resolvers.size())` is a no-op:
`i++` increments the local variable, which is lost, and the returned value is simply `i % resolvers.size()`
=> Fix load balancing

src/main/java/org/xbill/DNS/Cache.java
I have been seeing an error where in case of negative answer(NXDOMAIN), ttl of cache is being set at MINIMUM field of the SOA record (see [issue#186](https://github.com/dnsjava/dnsjava/issues/186)) whereas [RFC2308](https://tools.ietf.org/html/rfc2308), Section 3 says:
> The TTL of this record is set from the minimum of the MINIMUM field of the SOA record and the TTL of the SOA itself, and indicates how long a resolver may cache the negative answer.
I have explore the code and found out that it indeed is being set for MINIMUM field, I have added a fix for it to set the cache ttl at minimum of the MINIMUM field of the SOA record and the TTL of the SOA.
=> Fixed ttl for soa reacord to minimum of ttl and minimum field

src/main/java/org/xbill/DNS/DNSSEC.java
Hi Ingo,
I discovered that dnsjava was unable to create signatures for the ED25519 and ED448 algorithms. This pull request contains the fixes to make them work.
=> fixes to allow signing with ED25519 and ED448 algorithms

src/main/java/org/xbill/DNS/HTTPSRecord.java, src/main/java/org/xbill/DNS/SVCBBase.java, src/main/java/org/xbill/DNS/SVCBRecord.java, src/main/java/org/xbill/DNS/Type.java, src/test/java/org/xbill/DNS/HTTPSRecordTest.java, src/test/java/org/xbill/DNS/SVCBRecordTest.java
In the latest SVCB RFC draft (https://datatracker.ietf.org/doc/html/draft-ietf-dnsop-svcb-https-06), the parameter "echconfig" has been renamed to "ech".  This Pull Request implements that change for dnsjava, and renames the classes and variables appropriately.
=> Rename echconfig to ech in SVCB/HTTPS records

src/main/java/org/xbill/DNS/Name.java, src/test/java/org/xbill/DNS/NameTest.java
The Name.compareTo() function has a bug with its handling of octal digits byte values that are greater than 128. The lookup in the lowercase array was returning a signed byte that was implicitly cast to a signed int, resulting in a negative number. This would cause such values to be incorrectly treated as less than those in the 0-127 range.
This PR fixes the issue and adds test to verify the behavior. The fix is simply to perform another "& 0xFF" on the value that comes back from the lookup in the lowercase array. The octal_digits_high() test would previously have failed without this fix.
Also make a similar change in Name.hashCode().
=> Fix issue with Name compareTo and the handling of octal digit byte values

src/main/java/org/xbill/DNS/SVCBBase.java, src/test/java/org/xbill/DNS/SVCBRecordTest.java
Fixes #243
Remove incorrect check that required at least one param to be specified for ServiceMode records
Add unit tests to verify that ServiceMode records without any params are allowed and can be properly converted between text and wire formats
=> Allow SVCB ServiceMode records without params

src/main/java/org/xbill/DNS/Record.java, src/test/java/org/xbill/DNS/ARecordTest.java, src/test/java/org/xbill/DNS/RecordTest.java
Instead of relying on the unstable default Java serialization of each
record type, this uses a proxy object. The proxy object only contains
the DNS wire data of a record, which is guaranteed to be stable. This
avoids all concerns about compatibility when Record classes evolve and
with inheritance.
Closes #132
See #114
=> Make Record serializable again

src/main/java/org/xbill/DNS/SVCBBase.java
- Use replace instead of replaceAll for better performance as "," is not a regex. Also, "\\\\," is equivalent to "\\," hence the latter is used
- Loop entry set of Map instead of key set when both key and value of each entry are used in every iteration of the loop to safe an extra call of Map.get
=> Minor optimizations of SVCBBase

src/main/java/org/xbill/DNS/TXTBase.java, src/test/java/org/xbill/DNS/RecordTest.java
Instantiating an empty TXT record using Record.fromString() would
previously render as a TXT without the empty string.
Closes #254
=> Ensure that empty TXT records always renders as ""

src/main/java/org/xbill/DNS/SimpleResolver.java, src/test/java/org/xbill/DNS/SimpleResolverDeniedTest.java
When reading a response that is REFUSED with no more data. The code could crash while comparing the DNS query with the response.
This change skips the comparison if the response is denied.
=> Fix NPE in SimpleResolver

src/main/java/org/xbill/DNS/dnssec/DnsSecVerifier.java, src/main/java/org/xbill/DNS/dnssec/ValidatingResolver.java
Remove unreachable code to keep it simple as this is better for security code. Additionally, one simple typo is corrected for a private method.
=> Remove unreachable code

src/main/java/org/xbill/DNS/Zone.java, src/test/java/org/xbill/DNS/ZoneWithSoaSigTest.java
Associated issue: https://github.com/dnsjava/dnsjava/issues/334
Its a few lines of changes to "Zone.addRecord()" that allow for ingesting zones that have both a SOA and an associated RRSig/SOA.
Additionally, there's a test case that demonstrates the bug (fails on 3.6.1, works if the fix is applied).
=> fix bug in zone class wrt SOA/RRSig

README.adoc, src/main/java/org/xbill/DNS/hosts/HostsFileParser.java, src/test/java/org/xbill/DNS/hosts/HostsFileParserTest.java
Sometimes our/etc/hosts file is very large, and the machine's memory is large enough to load it into memory. At this point, we can customize this parameter.
=> support custom hosts file size

src/main/java/org/xbill/DNS/CNAMERecord.java
The `CNAMERecord` class has a constructor parameter for the CNAME target which is called `alias` at the moment. This is quite confusing, because:
- The API docs states that this parameter is "The name to which the CNAME alias points". So it is NOT the alias itself (which is the name of the record), but the target to which the record points.
- There is a deprecated method `CNAMERecord#getAlias()` which does NOT return the value supplied with the `alias` constructor parameter, but returns the name of the record instead.
I think it would be help to rename this parameter to `target`. That is also consistent with the name used in `NSRecord` and  `PTRRecord`.
=> Fixed confusing parameter name in CNAMERecord
